---
title: "Problem3"
runtime: shiny
output: html_document
---

# Commented Code for Problem 3

```{r}
library(pracma)
taylorPlot <- function(f, c, from, to) {
  # Plot the Taylor approximations up to the 2nd, 4th, 6th and 8th terms
  #
  # Parameters
  # ----------
  # f : function
  # Vectorized function of one variable
  # c : numeric
  # point where the series expansion will take place
  # from, to : numeric
  # Interval of points to be ploted
  #
  # Returns
  # -------
  # void
  
  x <- seq(from, to, length.out = 100)
  yf <- f(x)
  
  yp2 <- polyval(taylor(f, c, 2), x)
  yp4 <- polyval(taylor(f, c, 4), x)
  yp6 <- polyval(taylor(f, c, 6), x)
  yp8 <- polyval(taylor(f, c, 8), x)
  
  plot(
    x,
    yf,
    xlab = "x",
    ylab = "f(x)",
    type = "l",
    main = ' Taylor Series Approximation of f(x) ',
    col = "black",
    lwd = 2
  )
  
  lines(x, yp2, col = "#c8e6c9")
  lines(x, yp4, col = "#81c784")
  lines(x, yp6, col = "#4caf50")
  lines(x, yp8, col = "#388e3c")
  
  legend(
    'topleft',
    inset = .05,
    legend = c("TS 8 terms", "TS 6 terms", "TS 4 terms", "TS 2 terms", "f(x)"),
    col = c('#388e3c', '#4caf50', '#81c784', '#c8e6c9', 'black'),
    lwd = c(1),
    bty = 'n',
    cex = .75
  )
}
```

```{r}
f0 <- function(x) {
  res = sin(x)
  
  return(res)
  
}
```


```{r}
f1 <- function(x) {
  res = exp(complex(real = 0, imaginary = 1)*x)
  
  return(res)
  
}
```

```{r}
taylorPlot(f0, 0, -6.6, 6.6)
taylorPlot(f1, 1, -2*pi, 2*pi)
```


